### ISSUE TITLE
Create an RSS feed to allow subscriptions

### ISSUE THREAD

**Issue by AvAkanksh** [aakashns/aakashns.com#1]
Hey, Aakash your Blogs are great, I find them interesting, so please continue writing them. 
![image](https://github.com/aakashns/aakashns.com/assets/49116510/62e5f7f6-a29c-46bc-a7b4-6d23e96d7c29)

**Comment by AvAkanksh** [comment]
Also, it would be great if you could add an RSS feed to your blog/website so that interested people will follow them whenever you upload a new blog.

**Comment by aakashns** [comment]
Thanks @AvAkanksh, I'm glad you enjoyed reading the blog posts. I'm updating the title of the issue to "Create and RSS feed" and I'll try to look into it sometime soon.

**Comment by AvAkanksh** [comment]
Sure thing, Thanks 👍🏻

**Comment by aakashns** [comment]
The RSS feed has been added. Thanks for the suggestion!

<img width="813" alt="image" src="https://github.com/aakashns/aakashns.com/assets/1560745/253b1c80-7081-47fb-89b3-baf245fc7e34">
